version: '2'
services:
  niancat:
    image: erikedin/niancat:ready-for-acceptance
    environment:
      - DICTIONARY_FILE=/app/dictionary.txt
  niancatacceptance:
    build: .
    command: behave
    links:
      - niancat
