version: '2'
services:
  niancat:
    image: erikedin/niancat:ready-for-acceptance
    environment:
      - DICTIONARY_FILE=/app/dictionary.txt
    volumes:
      - ./dictionary.txt:/app/dictionary.txt
  niancat-slack:
    image: erikedin/niancat-slack:ready-for-acceptance
    links:
      - taut:slack.com
      - niancat
  taut:
    image: erikedin/taut
    environment:
      - SSL_CERT=/var/cert/cert.pem
      - SSL_KEY=/var/cert/key.pem
  niancatacceptance:
    build: .
    command: behave --tags=~wip
    links:
      - taut:slack.com
