swagger: "2.0"

info:
  version: 1.0.1
  title: Niancat
  description: API for the Niancat service.

schemes:
  - http
basePath: /v1

paths:
  /puzzle:
    get:
      summary: Get todays puzzle
      description: The puzzle consists of nine letters, which make up some word
                   in Swedish.
      produces:
        - application/json
      responses:
        200:
          description: Todays puzzle
          schema:
            type: string
            example: ABCDEFGHI
        404:
          description: Todays puzzle is not set.
        default:
          description: Unknown error
    post:
      summary: Set todays puzzle
      description: Setting the puzzle returns the last puzzle solution
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      - name: puzzle
        in: body
        description: The new puzzle.
        required: true
        schema:
          type: string
      responses:
        200:
          description: The puzzle was set and the last days puzzle is returned
          schema:
            type: object
            required:
              - puzzle
            properties:
              puzzle:
                type: string
              no_of_solutions:
                type: integer
              yesterdays_solution:
                type: array
                items:
                  $ref: '#/definitions/PreviousSolution'
              unsolutions:
                type: array
                items:
                  $ref: '#/definitions/UsersUnsolutions'

  /unsolution/{user}:
    get:
      summary: List all unsolutions for a user
      parameters:
      - name: user
        in: path
        description: Which user to list unsolutions for.
        required: true
        type: string
      responses:
        200:
          description: Returns a list of all unsolutions
          schema:
            type: array
            items:
              type: string

    post:
      summary: Store an unsolution for a user
      parameters:
      - name: user
        in: path
        description: The user for which to store the unsolution.
        required: true
        type: string
      - name: unsolution
        in: body
        description: The unsolution to store.
        required: true
        schema:
          type: string
      responses:
        200:
          description: Response stored.

definitions:
  UsersUnsolutions:
    type: object
    properties:
      user:
        type: string
      unsolutions:
        type: array
        items:
          type: string
  PreviousSolution:
    type: object
    properties:
      solution:
        type: string
      users:
        type: array
        items:
          type: string
