version: '2'
services:
  mockslack:
    build: .
    command: python3 /app/bin/mock_slack.py
  slackrest:
    build: .
    command: behave
    environment:
      - SLACK_API_TOKEN=0123456789abcdef
    links:
      - "mockslack:slack.com"
      - "mockchatbot:niancat-chat"
  mockchatbot:
    build: .
    command: python3 /app/bin/mock_chatbot.py